services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - custom_vol:/var/www/html

volumes:
  custom_vol:
    # external: true
