services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/
      - custom_vol:/var/www/html
      - type: volume
        source: second_volume
        target: /etc/nginx
        read_only: true

volumes:
  custom_vol:
    # external: true
  second_volume:
