services:
  nginx:
    image: nginx:latest
    container_name: cringenx
    environment:
      - one=1
      - two=2
    ports:
      - "8080:80"
      # - "443:443"
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d
      - custom_vol:/var/www/html
      # - type: volume
      #   source: second_volume
      #   target: /etc/nginx/conf.d
      #   read_only: true

volumes:
  custom_vol:
    # external: true
  # second_volume:
