services:
  nginx:
    container_name: cringenx
    devices:
      proxies:
      - connect: tcp:0.0.0.0:80
        listen: tcp:127.0.0.1:8080
    environment:
    - one=1
    - two=2
    image: docker:nginx:latest
    volumes:
    - read_only: false
      source: custom_vol
      target: /var/www/html
      type: volume
volumes:
  custom_vol:
    external: false
